### ISSUE TITLE
Request: forbid UnknownWord & remove last entry

### ISSUE THREAD

**Issue by n0o0ne** [philipp2310/snips-bring-shopping#11]
It would be nice that "UnknownWord" can't be added to your list. To pronounce it in german for removal is nearly impossible and if it is on your list it has no use. Because of the hassle to remove UnknownWord from my list i suggest a command to remove the last added entry would be a useful feature if the word is wrongly recognised. If bring! does not count maybe it's possible to combine it with the repeat the last command app.

**Comment by philipp2310** [comment]
Strangely I am not able to reproduce the "UnknownWord" issue.
Either I get something wrong added to the list, or I am asked "What do you want to add".
Is it some special word that it catches as UnknownWord and really uses as a slot value?

Regarding "undo last action", it would be awesome if it was possible to include it in "Wie Bitte?"/"Say it again". But unfortunately the undo action would be something different for every app/intent. I will keep it on my list, maybe we could agree on an interface that adds an "undo" command to the last heard request - then every app developer can implement it without any collisions in the intend detection. But if there is no specific implementation and it is only a slot value "undo", this would trigger the action again, instead of rolling it back.

As Bring! really isn't storing the time of adding the items, I need to store it in a local list.

I won't have the time to fix it in the next two weeks - but it will be the first task afterwards! Thanks for reporting!

**Comment by philipp2310** [comment]
Context sensitivity is part of Project Alice
